name: Build redocly HTML file
on: push
permissions:
  contents: read
jobs:
  run-redocly-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: petstore.yaml
          sparse-checkout-cone-mode: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npx -y @redocly/cli build-docs petstore.yaml -o output/redocly-static.html
      - uses: actions/upload-artifact@v3
        with:
          name: redocly-html
          path: output/redocly-static.html
